sudo: required

services:
    - docker

before_install:
  - docker-compose up --build --d

script:
  - echo "skipping tests"

after_success:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push catulam-frontend
  - docker push catulam-api
  - docker push catulam-db
