services:
    - docker

before_install:
  - docker-compose -f docker-compose-test.yml build

script:
  - docker-compose -f docker-compose-test.yml up

after_success:
  - docker-compose -f docker-compose-test.yml down --rmi all
  - docker-compose build
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker-compose push

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "catulam1"
  env: "catulam1-env"
  bucket_name: "elasticbeanstalk-eu-west-2-553268653483"
  bucket_path: "catulam1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
