version: '3'

services:
  neo4j:
    build: ./neo4j
    image: timt1/catulam-db
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/letmein
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_apoc_ttl_enabled=true
      - NEO4J_apoc_ttl_schedule=10
      - NEO4JLABS_PLUGINS=["apoc"]
  api:
    build: ./api
    image: timt1/catulam-api
    ports:
      - 4000:4000
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=letmein
      - GRAPHQL_LISTEN_PORT=4000
      - JWT_SECRET=catulam2A34iaeDwefdAaawe12s0wfha048
      - BCRYPTHASHCOST=10
      - NODE_ENV=production
      - CORS_ORIGIN=http://localhost
      - GRAPHQL_URI=http://localhost:4000/graphql
    links:
      - neo4j
    depends_on:
      - neo4j
  frontend:
    image: timt1/catulam-frontend
    build: ./frontend
    ports:
      - 80:80
    links:
      - api
    depends_on:
      - neo4j
      - api
