version: '3'

services:
  nginx:
    depends_on:
      - frontend
      - api
    restart: always # because it is routing traffic to our entire app
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: nginx
    ports:
      - 80:80

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend
    volumes:
      - /app/node_modules
    restart: on-failure

  api:
    depends_on:
      - neo4j
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - /app/node_modules
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=letmein
      - GRAPHQL_LISTEN_PORT=4000
      - JWT_SECRET=catulam2A34iaeDwefdAaawe12s0wfha048
      - BCRYPTHASHCOST=10
      - CORS_ORIGIN=http://localhost
      - GRAPHQL_URI=http://api:4000/graphql
      - NODE_ENV=production
    restart: on-failure

  neo4j:
    build:
      context: ./neo4j
      dockerfile: Dockerfile
    container_name: neo4j
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/letmein
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_apoc_ttl_enabled=true
      - NEO4J_apoc_ttl_schedule=10
      - NEO4JLABS_PLUGINS=["apoc"]
