version: '3'

services:
  frontend:

  api:

  db:
    build: ./db
      ports:
        - 7474:7474
        - 7687:7687
      environment:
        - NEO4J_dbms_security_procedures_unrestricted=apoc.*
        - NEO4J_apoc_import_file_enabled=true
        - NEO4J_apoc_export_file_enabled=true
        - NEO4J_dbms_shell_enabled=true
