version: '3'

networks:
  catLink:
    driver: bridge

services:

  neo4j:
      image: neo4j:latest
      ports:
        - 7474:7474
        - 7473:7473
        - 7687:7687
      volumes:
        - $HOME/neo4j/data:/data
        - $HOME/neo4j/logs:/logs
        - $HOME/neo4j/import:/var/lib/neo4j/import
        - $HOME/neo4j/conf:/conf
        - $HOME/neo4j/plugins:/plugins
      environment:
        - NEO4J_AUTH=neo4j/changeme
        - NEO4J_dbms_security_procedures_unrestricted=apoc.*
        - NEO4JLABS_PLUGINS=["apoc"]
      networks:
        - catLink

  api:
    build: ./api
    ports:
      - 7000:7000
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test
      - GRAPHQL_LISTEN_PORT=7000
      - GRAPHQL_URI=http://localhost:7000/graphql
    links:
      - neo4j
    depends_on:
      - neo4j
    networks:
      - catLink

