version: '3'

networks:
  catLink:
    driver: bridge
services:
  neo4j:
    container_name: catulam-db
    build: ./neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_apoc_ttl_enabled=true
      - NEO4J_apoc_ttl_schedule=10
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4JLABS_PLUGINS=["apoc"]
    networks:
      - catLink
  api:
    container_name: catulam-api
    build: ./api
    ports:
      - 7000:7000
    environment:
      - NEO4J_URI=bolt://catulam-db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=letmein
      - GRAPHQL_LISTEN_PORT=7000
      - GRAPHQL_URI=http://catulam-api:7000/graphql
      - JWT_SECRET=catulam2A34iaeDwefdAaawe12s0wfha048
      - BCRYPTHASHCOST=10
      - NODE_ENV=production
    links:
      - neo4j
    depends_on:
      - neo4j
    networks:
      - catLink
  frontend:
    container_name: catulam-frontend
    build: ./frontend
    ports:
      - 80:80
    links:
      - api
    depends_on:
      - neo4j
      - api
    networks:
      - catLink
