version: '3'

services:
  neo4j:
    build:
      context: ./neo4j
      dockerfile: Dockerfile
    container_name: neo4j
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/letmein
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_ttl_enabled=true
      - NEO4J_apoc_ttl_schedule=10
      - NEO4JLABS_PLUGINS=["apoc"]

  api:
    depends_on:
      - neo4j
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: api
    volumes:
      - /app/node_modules
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=letmein
      - GRAPHQL_LISTEN_PORT=4000
      - JWT_SECRET=catulam2A34iaeDwefdAaawe12s0wfha048
      - BCRYPTHASHCOST=10
      - GRAPHQL_URI=http://localhost:4000/graphql
      - NODE_ENV=production
      - DB_HOST=neo4j
    command: /bin/sh -c 'pwd'
#    command: ["/bin/sh", "-c", "ls", "/app/wait-for"]
#    command: ["/bin/sh", "-c", "ls"]
#    command: ["/bin/sh", "-c", "./wait-for", "neo4j:7687", "--", "npm", "test"]
#    command: ["ls", "./", "&&", "wait-for", "neo4j:7687", "--", "npm", "test"]
#    command: ["ls", "&&", "wait-for", "neo4j:7687", "--", "npm", "test"]
#    command: ["pwd", "&&", "ls", "&&", "wait-for", "neo4j:7687", "--", "npm", "test"]
#    command: sh -c 'wait-for neo4j:7687 -- npm test'
#    command: ["/app/wait-for", "neo4j:7687", "--", "npm", "test"]
#    command: ["/bin/sh","-c","wait-for", "neo4j:7687", "--", "npm", "test"]
#    command: ["wait-for.sh-it.sh", "neo4j:7687", "--", "npm", "test"]
#    command: sh -c './wait-for.sh-it.sh neo4j:7687 -- npm test'




