version: '3'

networks:
  catLink:
    driver: bridge

services:

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/conf:/conf
      - $HOME/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4JLABS_PLUGINS=["apoc"]
    networks:
      - catLink

  api:
    build: ./api
    ports:
      - 7000:7000
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test
      - GRAPHQL_LISTEN_PORT=7000
    links:
      - neo4j
    depends_on:
      - neo4j
    networks:
      - catLink

  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    environment:
      - VUE_APP_GRAPHQL_URI=http://0.0.0.0:7000/graphql
    links:
      - api
    depends_on:
      - neo4j
      - api
    networks:
      - catLink
