const express = require('express');
const { ApolloServer } = require('apollo-server-express');
const schema = require('./graphQL-schema');
const driver = require('./neo4jDriver');
const bcrypt = require('bcrypt');
// set environment variables from ../.env
require('dotenv').config();

const port = process.env.GRAPHQL_LISTEN_PORT;
const app = express();



/*
 * An executable GraphQL schema object from GraphQL type definitions
 * including autogenerated queries and mutations.
 */


const server = new ApolloServer({
    schema,
    context: { driver },
    introspection: true,
    playground: true,
});

// async function bycrpyt() {
//     const passwordHash = await bcrypt.hash('test', 12);
//     console.log(passwordHash);
//
// }
server.applyMiddleware({ app });

app.listen({ port }, () => console.log(`🚀 Server ready at http://localhost:${port}${server.graphqlPath}`));

