FROM node:lts-alpine

ENV NEO4J_URI=bolt://neo4j:7687 \
    NEO4J_USER=neo4j \
    NEO4J_PASSWORD=letmein \
    GRAPHQL_LISTEN_PORT=4000 \
    JWT_SECRET=catulam2A34iaeDwefdAaawe12s0wfha048 \
    BCRYPTHASHCOST=10 \
    CORS_ORIGIN=http://localhost \
    GRAPHQL_URI=http://localhost:4000/graphql

WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

RUN npm install

# copy project files and folders to the current working directory (i.e. 'api' folder)
COPY . .

EXPOSE 4000

CMD ["npm", "run", "test"]
